<?php

function etherex_mod_menu() {
  $items['chain'] = array(
    'access arguments' => array('access content'),
    'page callback' => 'etherex_mod_chain',
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function etherex_mod_chain() {
  // Get balance with RPC
  module_load_include('module', 'jsonrpc_client');

  $client = new JsonRpcClient(
    'http://54.204.10.41:8080',
    '2.0'
  );
  // $result = $client->call('balanceAt', array('a' => '0xe559de5527492bcb42ec68d07df0742a98ec3f1e'));
  // if (!empty($result['result'])){
  //   $balance = hexdec($result['result']);
  // }
  // watchdog('rpcbalance', var_export($result, TRUE) . ": " . $balance);

  $result = $client->call('lastBlock');
  if (empty($result) || empty($result['result']) || empty($result['result']['number'])) {
    return FALSE;
  }
  $max = 25;
  $last = $result['result']['number'];
  $blocks = array();
  $hash = $result['result']['hash'];
  $c = 0;
  for ($i=$last; $i > $last - $max; $i--) {
    $block = $client->call('block', array('a' => $hash));
    $block['result']['number'] = $block['result']['number'] - $c;
    $hash = $block['result']['parentHash'];
    // if ($block['result']['transactionsRoot'] != '0000000000000000000000000000000000000000000000000000000000000000') {
    //   $txcount = $client->call('txCountAt', array('a' => $block['result']['hash']))['result'];
    //   $block['result']['transactions'] = array();
    //   $block['result']['transactions'][] = hexdec($txcount);
    // }
    $blocks[] = $block['result'];
    $c++;
  }
  $header = array(
    "coinbase",
    "difficulty",
    "gasLimit",
    "gasUsed",
    "hash",
    "minGasPrice",
    "nonce",
    "number",
    "parentHash",
    "sha3Uncles",
    "stateRoot",
    "timestamp",
    "transactionsRoot"
  );
  return theme_table($header, $blocks);
  // return check_markup('<pre>' . json_encode($blocks, JSON_PRETTY_PRINT) . '</pre>');
}

function etherex_mod_form_simplenews_block_form_1_alter(&$form, &$form_state) {
  global $user;
  $submit_text = t('Stay tuned');
  if ($user->uid) {
    if (simplenews_user_is_subscribed($user->mail, 1)) { // 1 -> $tid
      $submit_text = t('Unsubscribe');
    }
  }
  // $form['donations'] = array(
  //   '#type' => 'markup',
  //   '#value' => '<h4>Donations<br/>1MMQbxMhyt3XvmArTiscWRZCsdwpv4nnuu</h4>'
  // );
  $form['submit']['#value'] = $submit_text;
}
